AarhusWebDevCoop/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AarhusWebDevCoop.ViewModels
{
    public class ContactForm
    {
        [Required(ErrorMessage ="Please enter your name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter your email address")]
        [Display(Name ="Email")]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$",
            ErrorMessage = "Please enter a correct email address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter a subject")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "Please enter a message")]
        public string Message { get; set; }
    }
}

AarhusWebDevCoop/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using Umbraco.Web.Mvc;
using AarhusWebDevCoop.ViewModels;
using Umbraco.Core;
using Umbraco.Core.Models;
using Umbraco.Core.Services;


namespace AarhusWebDevCoop.Controllers
{
    //inherits from the Surface Controller
    public class ContactFormSurfaceController : SurfaceController
    {
        [HttpGet]
        public ActionResult Index()
        {
            //display the partial view contact form
            return PartialView("_ContactForm", new ContactForm());
        }

        // post method that creates a new message, adds it to my email and selects the subject, email and the message from the form.
        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {
            MailMessage message = new MailMessage();
            message.To.Add("guille8.bcn@gmail.com");
            message.Subject = model.Subject;
            message.From = new MailAddress(model.Email, model.Name);
            message.Body = model.Message;

            // if we get errors we return the same page with the validation warnings and not an error page
            if (!ModelState.IsValid) { return CurrentUmbracoPage(); }

            
            // we use the smtp in order to send the message to my email
            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("guille8.bcn@gmail.com", "*********");
                // send mail 
                smtp.Send(message);
            }

            // We use the temporal variable to use it in the view so we know if the message was sent or not
            TempData["success"] = true;

            // This code creates a comment type document behind the message document and save all the messages received
                //gets the GuidUi of the current page
                GuidUdi currentPageUdi = new GuidUdi(CurrentPage.ContentType.ItemType.ToString(), CurrentPage.Key);

                // Creates the new content type
                IContent msg = Services.ContentService.CreateContent(model.Subject, currentPageUdi, "message");
                msg.SetValue("messageName", model.Name);
                msg.SetValue("email", model.Email);
                msg.SetValue("subject", model.Subject);
                msg.SetValue("messageContent", model.Message);
                msg.SetValue("umbracoNaviHide", true);

                Services.ContentService.Save(msg);

            return RedirectToCurrentUmbracoPage();
        }
        

    }
}

AarhusWebDevCoop/Views/AboutUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.AboutUs>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
}


<section id="one" class="wrapper style1" >
	<div class="container 100%">
		<div class="row 300%">
			<div class="">
                <h2></h2>
            </div>
        </div>
    </div>  
</section>


<div >
    @Html.GetGridHtml(Model, "ea") 
</div>

AarhusWebDevCoop/Views/ArticleItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ArticleItem>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
}



	<!-- Banner -->
			<section id="banner-articles">
			    <div class="container" >
				<h2>@Model.Value("articleTitle")</h2>
				</div>
				<br/>
				<p class="text-white">Last edited @Model.UpdateDate.ToString("dd/MM/yyyy")</p>
			</section>
			
			<section id="body-articles">
			    <div class="container" >
		        <p><br /><br /></p>
                <h2 class="text-center"><strong>@Model.Value("articleTitle")</strong></h2>
                <p><br /></p>
                @Model.Value("articleContent")
				</div>
				<br/>
			</section>


				<section id="four" class="wrapper style3 special">
					<div class="container">
						<header class="major">
							<h2></h2>
						</header>
						<ul class="actions">
							<li></li>
						</ul>
					</div>
				</section>

AarhusWebDevCoop/Views/ArticlesOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ArticlesOverview>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
}

<!-- Three -->
				<section id="three" class="wrapper style1">
					<div class="container">
						<header class="major special">
							<h2>Articles Overview</h2>
							<p>Have a look at our articles</p>
						</header>
						<div class="feature-grid">
							<div class="feature">
								<div class="image rounded"><img src="images/pic04.jpg" alt="" /></div>
								<div class="content">
									<header>
										<h4>Lorem ipsum</h4>
										<p>Lorem ipsum dolor sit</p>
									</header>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore esse tenetur accusantium porro omnis, unde mollitia totam sit nesciunt consectetur.</p>
								</div>
							</div>
							<div class="feature">
								<div class="image rounded"><img src="images/pic05.jpg" alt="" /></div>
								<div class="content">
									<header>
										<h4>Recusandae nemo</h4>
										<p>Ratione maiores a, commodi</p>
									</header>
									<p>Animi mollitia optio culpa expedita. Dolorem alias minima culpa repellat. Dolores, fuga maiores ut obcaecati blanditiis, at aperiam doloremque.</p>
								</div>
							</div>
							<div class="feature">
								<div class="image rounded"><img src="images/pic06.jpg" alt="" /></div>
								<div class="content">
									<header>
										<h4>Laudantium fugit</h4>
										<p>Possimus ex reprehenderit eaque</p>
									</header>
									<p>Maiores iusto inventore fugit architecto est iste expedita commodi sed, quasi feugiat nam neque mollitia vitae omnis, ea natus facere.</p>
								</div>
							</div>
							<div class="feature">
								<div class="image rounded"><img src="images/pic07.jpg" alt="" /></div>
								<div class="content">
									<header>
										<h4>Porro aliquam</h4>
										<p>Quaerat, excepturi eveniet laboriosam</p>
									</header>
									<p>Vitae earum unde, autem labore voluptas ex, iste dolorum inventore natus consequatur iure similique obcaecati aut corporis hic in! Porro sed.</p>
								</div>
							</div>
						</div>
					</div>
				</section>

			<!-- Four -->
				<section id="four" class="wrapper style3 special">
					<div class="container">
						<header class="major">
							<h2>Aenean elementum ligula</h2>
							<p>Feugiat sed lorem ipsum magna</p>
						</header>
						<ul class="actions">
							<li><a href="#" class="button special big">Get in touch</a></li>
						</ul>
					</div>
				</section>

AarhusWebDevCoop/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ContactPage>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
}

<section id="one" class="wrapper style1" >
	<div class="container 100%">
			<div class="row 300%" style="padding-top: 10%">
				<div class="8u 10u$(medium) -2u">
                <h2>@Model.Name</h2>
                
                <div>
                    @Html.Action("Index","ContactFormSurface")
                </div>
                </div>
                </div>
                </div>
</section>

AarhusWebDevCoop/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
}

  
	<!-- Banner -->
			<section id="banner">
				<h2>@Model.Value("siteTitle")</h2>
				
				<ul class="actions">
					<li><a href="/login" class="button special big">Enter</a></li>
				</ul>
			</section>
			
			<!-- One -->
				<section id="one" class="wrapper style1">
					<div class="container 100%">
						<div class="row 200%">
							<div class="6u 12u$(medium)">
								<header class="major">
									<h2>@Model.Value("siteTitle")</h2>
									<p>By @Model.Value("autor")</p>
									
								</header>
								<p class="">@Model.Value("mainContent")</p>

							</div>
							
                                <img src="@Model.Value("homeImage")" class="6u$ 12u$(medium)">				    
							
						</div>
					</div>
				</section>

			<!-- Two -->
				<!--<section id="two" class="wrapper style2 special">-->
				<!--	<div class="container">-->
				<!--		<header class="major">-->
				<!--			<h2>Fusce ultrices fringilla</h2>-->
				<!--			<p>Maecenas vitae tellus feugiat eleifend</p>-->
				<!--		</header>-->
				<!--		<div class="row 150%">-->
				<!--			<div class="6u 12u$(xsmall)">-->
				<!--				<div class="image fit captioned">-->
				<!--					<img src="/images/pic02.jpg" alt="" />-->
				<!--					<h3>Lorem ipsum dolor sit amet.</h3>-->
				<!--				</div>-->
				<!--			</div>-->
				<!--			<div class="6u$ 12u$(xsmall)">-->
				<!--				<div class="image fit captioned">-->
				<!--					<img src="/images/pic03.jpg" alt="" />-->
				<!--					<h3>Illum, maiores tempora cupid?</h3>-->
				<!--				</div>-->
				<!--			</div>-->
				<!--		</div>-->
				<!--		<ul class="actions">-->
				<!--			<li><a href="#" class="button special big">Nulla luctus</a></li>-->
				<!--			<li><a href="#" class="button big">Sed vulputate</a></li>-->
				<!--		</ul>-->
				<!--	</div>-->
				<!--</section>-->

			<!-- Project List -->
				
					<!-- Three -->
            <section id="three" class="wrapper style1">
            	<div class="container">
            		<header class="major special">
            			<h2>Projects</h2>
            			<p>Projects</p>
            		</header>
            		<div class="feature-grid">	    
                            @Html.Partial("~/Views/Partials/projectList.cshtml")
            							
            		</div>
            	</div>
            </section>	

			<!-- Four -->
				<section id="four" class="wrapper style3 special">
					<div class="container">
						<header class="major">
							<h2>Get in touch with us</h2>
						</header>
						<ul class="actions">
							<li><a href="/contact-us" class="button special big">Contact us</a></li>
						</ul>
					</div>
				</section>

AarhusWebDevCoop/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Login>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
}



<section id="one" class="wrapper style1" >
	<div class="container 100%">
			<div class="row 300%" style="padding-top: 10%">
				<div class="8u 10u$(medium) -2u">
                <h2>@Model.Name</h2>
                
                <div>
                    @Html.Partial("~/Views/Partials/_loginForm.cshtml") 
                </div>
                </div>
                </div>
                </div>
</section>

AarhusWebDevCoop/Views/MacroPartials/Dropdown2.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Core.Models.PublishedContent

@using Umbraco.Web

@{

var root = Model.Content.Root();

var selection = root.AncestorOrSelf(2).Children.Where(x => x.IsVisible()).ToArray();

}

<ul class="navbar-nav ml-auto navbar-right flex-row">

<li class ="nav-item @(Model.Content.Name == root.Name ? "active" : null) ">

<a class="nav-link" href="@root.Url">@root.Name</a> 

</li>

@if (selection.Length > 0) { 

foreach (var menuItem in selection)

    {
    
    //Children of the root
    
    if (menuItem.Children().Where(x => x.IsVisible()).Count() > 0)
    
    {
    
    <li class="nav-item dropdown @(menuItem.IsAncestorOrSelf(Model.Content) ? "selected" : null)">
    
    <a class="nav-link dropdown-toggle" href="@menuItem.Url" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
    
    @menuItem.Name
    
    </a>
    
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    
    @foreach (var subItem in menuItem.Children().Where(x => x.IsVisible()))
    
    {
        
        // if document type is ProjectItem
        
        if(subItem.IsDocumentType("ProjectItem"))
        
        {
        <!--if active user, see all projects-->
        if (Members.IsLoggedIn()){
            <a class="dropdown-item" href="@subItem.Url">@subItem.Name</a>
        
        
        <!--If guest, see just completed projects-->
        <!--and if Project status is completed-->
        
            } else if (subItem.HasValue("projectStatus") && subItem.GetProperty("projectStatus").Value<string>() == "Completed" && subItem.IsVisible())
            
            {
            
            <a class="dropdown-item" href="@subItem.Url">@subItem.Name</a>
            
            }
            
            }
            
            //else display subItem as before
            
            else{
            
            <a class="dropdown-item" href="@subItem.Url">@subItem.Name</a> 
            
            }
    
    }
    
    </div>
    
    </li>

    }

else

{

<li class="nav-item @(menuItem.IsAncestorOrSelf(Model.Content) ? "active" : null)"> 

<a class="nav-link" href="@menuItem.Url">@menuItem.Name</a> 

</li> 

}

}

}

</ul>

AarhusWebDevCoop/Views/MacroPartials/imageRenderer.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@*
    Macro to display a series of images from a media folder.

    How it works:
        - Confirm the macro parameter has been passed in with a value
        - Loop through all the media Ids passed in (might be a single item, might be many)
        - Display any individual images, as well as any folders of images

    Macro Parameters To Create, for this macro to work:
    Alias:mediaId     Name:Select folder with images    Type:Single Media Picker
*@

@{ var mediaId = Model.MacroParameters["1156"]; }

@if (mediaId != null)
{
    @* Get the media item associated with the id passed in *@
    var media = Umbraco.Media(mediaId);
    var selection = media.Children.ToArray();

    if (selection.Length > 0)
    {
        <ul>
            @foreach (var item in selection)
            {
                <li>
                    <img src="@item.Url" alt="@item.Name" />
                </li>
            }
        </ul>
    }
}

AarhusWebDevCoop/Views/MacroPartials/listNewestProjects.cshtml
@using ContentModels = Umbraco.Web.PublishedModels;
@using Umbraco.Web;
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    var startNodeId = Model.MacroParameters["startNodeId"] != null ? Model.MacroParameters["startNodeId"] : Model.Content.Id;


    var numberOfPosts = 3;
    if (Model.MacroParameters["numberOfPosts"] != null)
    {
        int.TryParse((string)Model.MacroParameters["numberOfPosts"], out numberOfPosts);
    }


}
@if (startNodeId != null)
{
    @* Get the starting page *@
    var startNode = Umbraco.Content(startNodeId);

    if (startNode == null)
    {
        <div class="blogposts">
            <h1>There are no posts at this time, try again later.</h1>
        </div>

        return;
    }

    //Gets all blogposts to calculate pages
    var blogposts = startNode.Children.OrderBy(x => x.CreateDate).ToList();
    var pageCount = (int)Math.Ceiling((double)blogposts.Count / (double)numberOfPosts);
    //gets the page from the querystring and sets it to one if it is out of range
    var page = 1;
    if (!string.IsNullOrEmpty(Request.QueryString["page"]))
    {
        int.TryParse(Request.QueryString["page"], out page);
        if (page <= 0 || page > pageCount)
        {
            page = 1;
        }
    }
    //Gets the blogposts for the current page
    var pagedBlogposts = blogposts.Skip((page - 1) * numberOfPosts).Take(numberOfPosts).ToList();

    if (pagedBlogposts.Count > 0)
    {
        <div class="blogposts">

            @foreach (ContentModels.Blogpost post in pagedBlogposts)
            {
                <a href="@post.Url" class="blogpost">
                    <div class="blogpost-meta">
                        <small class="blogpost-date">@post.CreateDate.ToShortDateString()</small>
                        <small class="blogpost-cat">
                            @Html.Partial("~/Views/Partials/CategoryLinks.cshtml", post.Categories)
                        </small>
                    </div>
                    <h3 class="blogpost-title">@post.PageTitle</h3>
                    <div class="blogpost-excerpt">@post.Excerpt</div>
                </a>
            }
        </div>
    }

    if (blogposts.Count > numberOfPosts)
    {
        <div class="pagination">
            <nav class="nav-bar nav-bar--center">
                @if (page <= 1)
                {
                    <span class="nav-link nav-link--black nav-link--disabled">Prev</span>
                }
                else
                {
                    <a class="nav-link nav-link--black" href="@(Model.Content.Url + "?page=" + (page - 1))">Prev</a>
                }

                @for (int i = 1; i <= pageCount; i++)
                {
                    <a class="nav-link nav-link--black @(page == i ? " nav-link--active" : null)" href="@(Model.Content.Url + "?page=" + i)">@i</a>
                }
                @if (page == pageCount)
                {
                    <span class="nav-link nav-link--black nav-link--disabled">Next</span>
                }
                else
                {
                    <a class="nav-link nav-link--black" href="@(Model.Content.Url + "?page=" + (page + 1))">Next</a>
                }

            </nav>
        </div>
    }
}

AarhusWebDevCoop/Views/MacroPartials/navigationTest.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web


@*
    This snippet displays a list of links of the pages immediately under the top-most page in the content tree.
    This is the home page for a standard website.
    It also highlights the current active page/section in the navigation with the CSS class "current".
*@

@{ var selection = Model.Content.Root().Children.Where(x => x.IsVisible()).ToArray(); }

@if (selection.Length > 0)
{
    <ul>
        @foreach (var item in selection)
        {
            <li class="@(item.IsAncestorOrSelf(Model.Content) ? "current" : null)">
                <a href="@item.Url">@item.Name</a>
            </li>
        }
    </ul>
}

AarhusWebDevCoop/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
	Layout = null;
}

<!DOCTYPE HTML>

<html>
	<head>
		<title>Aarhus Web Developer Corporation</title>
		<meta charset="utf-8" />
		<meta name="description" content="Aarhus Web Developer Corporation">
        <meta name="keywords" content="Aarhus, Web Developer, Corporation">
        <meta name="author" content="Guillem Pujol">
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="/assets/css/main.css" />
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	</head>
    <body class="landing">



        <!-- Header -->
        <header id="header" class="alt">
            <div class="container">
                <img src="../../images/logo1.png" height="100" width="151" id="logo"><a href="index.html"></a></img>


                <!-- Nav Bar -->
                <nav class="nav-bar top-nav d-flex justify-content-end flex-row">
                    @Umbraco.RenderMacro("Dropdown2")
                </nav>
            </div>


        </header>

        <a href="#menu" class="navPanelToggle"><span class="fa fa-bars"></span></a>




        @RenderBody()

        <!-- Footer -->
        <footer id="footer">
            <div class="container">
                <ul class="icons">
                    <li><a href="#" class="icon fa-facebook"></a></li>
                    <li><a href="#" class="icon fa-twitter"></a></li>
                    <li><a href="#" class="icon fa-instagram"></a></li>
                </ul>
                <ul class="copyright">
                    <li>&copy; BAAA</li>
                    <li></a></li>
                    <li></a></li>
                </ul>
            </div>
        </footer>

        <!-- Scripts -->

        <script src="/Scripts/jquery-3.4.1.slim.min.js"></script>
        <!--
    <script src="Scripts/popper.min.js"></script>
    <script src="Scripts/bootstrap.min.js"></script>-->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <!--<script src="/assets/js/jquery.min.js"></script>-->
        <script src="/assets/js/skel.min.js"></script>
        <script src="/assets/js/util.js"></script>
        <script src="/assets/js/main.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    </body>
</html>

AarhusWebDevCoop/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Members>
@using ContentModels = Umbraco.Web.PublishedModels;
@using Umbraco.Core;
@using Umbraco.Core.Models;
@using Umbraco.Core.Services;
@{
	Layout = "Master.cshtml";
	IMemberService memberService = Services.MemberService;

    var members = memberService.GetMembersByGroup("Active");
}



<section id="one" class="wrapper style1" >
  
</section>


<div class="container">
@foreach (var member in members) {

    <img src="@member.GetValue("photo")">
    <img @member.GetValue("photo2")>
    <p>
    @member.Name <br>
    @member.GetValue("address") <br>
    @member.GetValue("zip") 
    @member.GetValue("city") <br>
    Email: @member.Email <br>
    </p>
        // member.GetValue("skills").ToString(). E.g.: ["AngularJS","CSS","ASP.NETMVC","PHP"]
    if (member.GetValue("skills") != null) {
    string[] skills = member.GetValue("skills").ToString().Split(',');
    string skillString = string.Join(", ", skills.Select(item => item)).Replace("\"", "").TrimStart('[').TrimEnd(']');
    <span>Skills: @skillString</span> <br>
    <br/>
}
}
    </div>

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row);
                    }
                </div>
            }   
        }else { 
            <div class="row clearfix">
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

AarhusWebDevCoop/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;
    
    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

AarhusWebDevCoop/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.TextPage>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
}